# ==============================================================================
# WorkAdventure Docker Setup Helper (Windows PowerShell)
# ==============================================================================

function Get-RandomSecret {
    $bytes = New-Object byte[] 32
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($bytes)
    return ($bytes | ForEach-Object { "{0:x2}" -f $_ }) -join ''
}

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "    WorkAdventure Docker Setup Helper (Windows)   " -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

param (
    [string]$Mode = "",
    [string]$Domain = "",
    [string]$Email = ""
)

if (-not $Mode) {
    Write-Host "Select target environment:"
    Write-Host "  1) Local testing (http://localhost, no SSL needed)"
    Write-Host "  2) Production VPS (https://your-domain.com with Let's Encrypt)"
    $choice = Read-Host "Enter choice [1 or 2]"
    switch ($choice) {
        "1" { $Mode = "local" }
        "2" { $Mode = "prod" }
        default { Write-Error "Invalid choice. Exiting."; exit 1 }
    }
}

$secretKey = Get-RandomSecret
$adminToken = Get-RandomSecret
$mapToken = Get-RandomSecret

if ($Mode -eq "local") {
    $Domain = "localhost"
    $Email = "local@localhost.test"
    Write-Host "`n==> Configuring for LOCAL environment (localhost)..." -ForegroundColor Green
} else {
    if (-not $Domain) {
        $Domain = Read-Host "Enter your domain name (e.g. office.yourcompany.com)"
    }
    if (-not $Email) {
        $Email = Read-Host "Enter your email for Let's Encrypt SSL certificates"
    }
    Write-Host "`n==> Configuring for PRODUCTION environment ($Domain)..." -ForegroundColor Green
}

$envContent = @"
# Auto-generated by docker-setup.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
DOMAIN=$Domain
ACME_EMAIL=$Email
SECRET_KEY=$secretKey
ADMIN_API_TOKEN=$adminToken
MAP_STORAGE_API_TOKEN=$mapToken
AUTHENTICATION_TOKEN=$mapToken
ROOM_API_SECRET_KEY=$secretKey

VERSION=v1.33.5
HTTP_PORT=80
HTTPS_PORT=443
GRPC_PORT=50051

START_ROOM_URL=/_/global/workadventure.github.io/map-starter-kit/office.tmj
JITSI_URL=meet.jit.si
JITSI_PRIVATE_MODE=false
STUN_SERVER=stun:stun.l.google.com:19302

ENABLE_MAP_EDITOR=true
MAP_EDITOR_ALLOW_ALL_USERS=true
ENABLE_CHAT=true
ENABLE_CHAT_UPLOAD=true
ENABLE_CHAT_ONLINE_LIST=true
ENABLE_CHAT_DISCONNECTED_LIST=true
ENABLE_TUTORIAL=true
DISABLE_ANONYMOUS=false
MAX_PER_GROUP=4
GROUP_RADIUS=48
MINIMUM_DISTANCE=64
RESTART_POLICY=unless-stopped
LOG_LEVEL=INFO
UPLOAD_MAX_FILESIZE=10485760
"@

Set-Content -Path ".env" -Value $envContent -Encoding UTF8

Write-Host "==> Successfully created .env file with fresh random security keys!`n" -ForegroundColor Green

if ($Mode -eq "local") {
    Write-Host "To start WorkAdventure LOCALLY:" -ForegroundColor Yellow
    Write-Host "  docker compose -f docker-compose.standalone.yaml -f docker-compose.local.yaml up -d"
    Write-Host "`nThen open your browser at:" -ForegroundColor Cyan
    Write-Host "  http://localhost`n" -ForegroundColor White
} else {
    Write-Host "To start WorkAdventure in PRODUCTION:" -ForegroundColor Yellow
    Write-Host "  docker compose -f docker-compose.standalone.yaml up -d"
    Write-Host "`nMake sure your domain DNS ('$Domain') points to this server's public IP." -ForegroundColor Yellow
    Write-Host "Traefik will automatically issue a Let's Encrypt SSL certificate."
    Write-Host "Then open your browser at:" -ForegroundColor Cyan
    Write-Host "  https://$Domain`n" -ForegroundColor White
}
Write-Host "==================================================" -ForegroundColor Cyan
