#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# WorkAdventure Docker Setup Helper (Linux / macOS / WSL)
# ==============================================================================

generate_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    else
        python3 -c "import secrets; print(secrets.token_hex(32))"
    fi
}

echo "=================================================="
echo "    WorkAdventure Docker Setup Helper            "
echo "=================================================="

MODE="${1:-}"
if [ -z "$MODE" ]; then
    echo "Select target environment:"
    echo "  1) Local testing (http://localhost, no SSL needed)"
    echo "  2) Production VPS (https://your-domain.com with Let's Encrypt)"
    read -r -p "Enter choice [1 or 2]: " CHOICE
    case "$CHOICE" in
        1) MODE="local" ;;
        2) MODE="prod" ;;
        *) echo "Invalid choice. Exiting."; exit 1 ;;
    esac
fi

SECRET_KEY=$(generate_secret)
ADMIN_TOKEN=$(generate_secret)
MAP_TOKEN=$(generate_secret)

if [ "$MODE" = "local" ]; then
    DOMAIN="localhost"
    ACME_EMAIL="local@localhost.test"
    echo ""
    echo "==> Configuring for LOCAL environment (localhost)..."
else
    DOMAIN="${2:-}"
    if [ -z "$DOMAIN" ]; then
        read -r -p "Enter your domain name (e.g. office.yourcompany.com): " DOMAIN
    fi
    ACME_EMAIL="${3:-}"
    if [ -z "$ACME_EMAIL" ]; then
        read -r -p "Enter your email for Let's Encrypt SSL certificates: " ACME_EMAIL
    fi
    echo ""
    echo "==> Configuring for PRODUCTION environment (${DOMAIN})..."
fi

cat <<EOF > .env
# Auto-generated by docker-setup.sh on $(date -u)
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}
SECRET_KEY=${SECRET_KEY}
ADMIN_API_TOKEN=${ADMIN_TOKEN}
MAP_STORAGE_API_TOKEN=${MAP_TOKEN}
AUTHENTICATION_TOKEN=${MAP_TOKEN}
ROOM_API_SECRET_KEY=${SECRET_KEY}

VERSION=v1.33.5
HTTP_PORT=80
HTTPS_PORT=443
GRPC_PORT=50051

START_ROOM_URL=/_/global/workadventure.github.io/map-starter-kit/office.tmj
JITSI_URL=meet.jit.si
JITSI_PRIVATE_MODE=false
STUN_SERVER=stun:stun.l.google.com:19302

ENABLE_MAP_EDITOR=true
MAP_EDITOR_ALLOW_ALL_USERS=true
ENABLE_CHAT=true
ENABLE_CHAT_UPLOAD=true
ENABLE_CHAT_ONLINE_LIST=true
ENABLE_CHAT_DISCONNECTED_LIST=true
ENABLE_TUTORIAL=true
DISABLE_ANONYMOUS=false
MAX_PER_GROUP=4
GROUP_RADIUS=48
MINIMUM_DISTANCE=64
RESTART_POLICY=unless-stopped
LOG_LEVEL=INFO
UPLOAD_MAX_FILESIZE=10485760
EOF

echo "==> Successfully created .env file with fresh random security keys!"
echo ""

if [ "$MODE" = "local" ]; then
    echo "To start WorkAdventure LOCALLY:"
    echo "  docker compose -f docker-compose.standalone.yaml -f docker-compose.local.yaml up -d"
    echo ""
    echo "Then open your browser at:"
    echo "  http://localhost"
else
    echo "To start WorkAdventure in PRODUCTION:"
    echo "  docker compose -f docker-compose.standalone.yaml up -d"
    echo ""
    echo "Make sure your domain DNS ('${DOMAIN}') points to this server's public IP."
    echo "Traefik will automatically issue a Let's Encrypt SSL certificate."
    echo "Then open your browser at:"
    echo "  https://${DOMAIN}"
fi
echo "=================================================="
